---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/app
  - ../../components/db
  - ../../components/redis
  - db-secret.yaml
namespace: "octobox"
namePrefix: "octobox-"
images:
  - name: "octoboxio/octobox"
    newTag: "june-2023"
  - name: "docker.io/bitnami/postgresql"
    newTag: "15.3.0-debian-11-r9"
  - name: "docker.io/bitnami/redis"
    newTag: "6.2.12"
configMapGenerator:
  - name: app-config
    envs:
      - "app-config.env"
  # we're going to trigger the rollout by additionally having a generated
  # config map that changes when the sealed secret is updated.
  # See: https://github.com/kubernetes-sigs/kustomize/issues/702
  - name: db-sentinel
    files:
      - db-secret.yaml
  # for configuring the db statefulset
  - name: db-config
    envs:
      - db-config.env
  # for configuring app(s) to talk to the db
  - name: db-connect
    envs:
      - db-connect.env
